export {
  type AttachmentData,
  type AttachmentInfo,
  type BatchMessageResult,
  type Draft,
  type DraftInput,
  type DraftMessage,
  decodeBody,
  type Filter,
  type FilterAction,
  type FilterCriteria,
  GmailClient,
  getHeader,
  getHtmlBody,
  getTextBody,
  type Label,
  type Message,
  type MessageHeader,
  type MessagePart,
  type MessageSummary,
  type ReplyInput,
  type SearchResult,
  type SentMessage,
  type Thread,
  type VacationSettings,
} from './client.js';

export {
  buildDraftWithAttachments,
  buildRawMessage,
  encodeMimeHeader,
  type MimeAttachment,
  type MimeMessageOptions,
} from './mime.js';
