export {
  buildConferenceData,
  CalendarClient,
  type CalendarEvent,
  type CalendarInfo,
  type CalendarList,
  type ColorPalette,
  type ConferenceData,
  type ConferenceEntryPoint,
  type ConferencingRequest,
  type EventAttendee,
  type EventDateTime,
  type EventInput,
  type EventList,
  type EventUpdate,
  type FreeBusyResult,
  normalizeMeetingCode,
  type PaletteColor,
} from './client.js';
export { EVENT_COLOR_NAMES, resolveEventColorId } from './colors.js';
